# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: ruderphilipp/jmc.git
        ref: main
    - name: Check out the triggering repository
      run: |
         declare -A SUBMODULES=( \
            [jameica]=jameica \
            [datasource]=lib/datasource \
            [util]=lib/util \
            [example]=plugins/example \
            [hibiscus]=plugins/hibiscus \
            )

         set -x
         REPONAME=${GITHUB_REPOSITORY#*/}
         SUBREPOPATH=${SUBMODULES[$REPONAME]}
         echo "SUBREPOPATH=${SUBREPOPATH}" >> $GITHUB_ENV

         if [ ${REPONAME} = "jmc" ]; then
            echo "Github Actions run started from this repository"
         else
            git -C ${SUBREPOPATH} remote add action_repo git@github.com:${GITHUB_REPOSITORY}
            git -C ${SUBREPOPATH} fetch action_repo ${GITHUB_SHA}
            git -C ${SUBREPOPATH} checkout ${GITHUB_SHA}
         fi
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      run: gradle build
    - name: Copy build artifacts
      run: mkdir artifacts; cp -v ${SUBREPOPATH}/build/target/*.jar artifacts/
    - name: upload package
      uses: actions/upload-artifact@master
      with:
        name: pkg
        path: 'artifacts/*'

