# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Trigger on Push and pull requests
# but only if relevant code changes
on:
  push:
    branches: [ main ]
    paths:
      - '**.java'
      - '**.gradle'
  pull_request:
    branches: '*'
    paths:
      - '**.java'
      - '**.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: ruderphilipp/jmc.git
        ref: main
    - name: Check out the triggering repository
      run: |
         declare -A SUBMODULES=( \
            [jameica]=jameica \
            [datasource]=lib/datasource \
            [util]=lib/util \
            [example]=plugins/example \
            [hibiscus]=plugins/hibiscus \
            )

         set -x
         REPONAME=${GITHUB_REPOSITORY#*/}
         if [ ${REPONAME} = "jmc" ]; then
            echo "Github Actions run started from this repository"
         else
            git -C ${SUBMODULES[$REPONAME]} remote add action_repo git@github.com:${GITHUB_REPOSITORY}
            git -C ${SUBMODULES[$REPONAME]} fetch action_repo ${GITHUB_SHA}
            git -C ${SUBMODULES[$REPONAME]} checkout ${GITHUB_SHA}
         fi
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      run: gradle build test
    - name: upload package
      uses: actions/upload-artifact@master
      with:
        name: pkg
        path: 'plugins/hibiscus/build/target/*.jar'
